### ISSUE TITLE
Suggestion add example of animated list

### ISSUE THREAD

**Issue by realkalash** [astoniocom/list_controller#1]
Just a suggestion to add an example of how to implement [AnimationList](https://m.youtube.com/watch?v=ZtfItHwFlZ8)  with your dependency. As I understand this can be achived using the HotList implementation.

This would be very helpful for beginners and also great addition to the Readme.

**Comment by astoniocom** [comment]
Yeah, that's a great idea. I'll try to do it in the near future.

**Comment by astoniocom** [comment]
New example is [here](https://astoniocom.github.io/list_controller/#/animated_list)
